"""Versioned, point-in-time Beta policy and research-price helpers.

The dashboard consumes only an approved policy document.  Candidate building
is deliberately separate so a new estimate can never silently become a live
risk input.  Prices are normalised from raw executable closes plus explicit
split/dividend events; provider ``Adj Close`` values are never accepted.
"""

from __future__ import annotations

from datetime import date, datetime, timedelta, timezone
import hashlib
import json
import math
import time
from pathlib import Path
from typing import Any, Mapping

import requests

from risk import estimate_beta_from_returns, quarterly_half_kelly


POLICY_SCHEMA_VERSION = 1
MIN_WEEKLY_OBSERVATIONS = 104
DEFAULT_ACTIVE_POLICY_PATH = "config/beta-policy-active.json"
DEFAULT_ACTIVE_KELLY_PATH = "config/kelly-policy-active.json"
FIXED_BETAS = {"006208": 1.0, "00685L": 2.0}
OTC_SYMBOLS = {"00886", "3455"}


def _finite(value: Any) -> float | None:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    return number if math.isfinite(number) else None


def _as_date(value: Any) -> date | None:
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    text = str(value or "").strip()
    if not text:
        return None
    try:
        return date.fromisoformat(text[:10].replace("/", "-"))
    except ValueError:
        return None


def _symbol(value: Any) -> str:
    return str(value or "").strip().upper()


def yahoo_chart_symbols(symbol: str, market: str) -> tuple[str, ...]:
    """Return deterministic raw-chart symbols without yfinance state."""
    key = _symbol(symbol)
    if str(market).lower() in {"tw", "taiwan", "twd"}:
        preferred = "TWO" if key in OTC_SYMBOLS else "TW"
        alternate = "TW" if preferred == "TWO" else "TWO"
        return (f"{key}.{preferred}", f"{key}.{alternate}")
    if str(market).lower() in {"us", "usa", "usd"}:
        return (key,)
    return (key,)


def fetch_yahoo_research_series(
    symbol: str,
    *,
    market: str,
    start: date,
    end: date,
    http_get: Any = None,
    attempts: int = 3,
    timeout: float = 15,
    sleep_fn: Any = time.sleep,
) -> dict[str, Any]:
    """Fetch raw OHLC and explicit events for candidate construction.

    This endpoint is used only as a raw-history transport.  The returned
    contract never reads ``adjclose`` and always exposes a normalized research
    price generated by :func:`normalize_research_price`.
    """
    getter = http_get or requests.get
    failures: list[str] = []
    period1 = int(datetime.combine(start, datetime.min.time(), tzinfo=timezone.utc).timestamp())
    period2 = int(datetime.combine(end + timedelta(days=1), datetime.min.time(), tzinfo=timezone.utc).timestamp())
    for chart_symbol in yahoo_chart_symbols(symbol, market):
        for attempt in range(max(1, attempts)):
            try:
                response = getter(
                    f"https://query1.finance.yahoo.com/v8/finance/chart/{chart_symbol}",
                    params={"period1": period1, "period2": period2, "interval": "1d", "events": "history,splits,div"},
                    headers={"User-Agent": "Mozilla/5.0"},
                    timeout=timeout,
                )
                response.raise_for_status()
                payload = response.json()
                result = payload["chart"]["result"][0]
                timestamps = result.get("timestamp") or []
                quote = (result.get("indicators") or {}).get("quote", [{}])[0]
                closes = quote.get("close") or []
                rows = []
                for index, timestamp in enumerate(timestamps):
                    try:
                        item_date = datetime.fromtimestamp(float(timestamp), tz=timezone.utc).date()
                    except (TypeError, ValueError, OverflowError, OSError):
                        continue
                    if index >= len(closes) or _finite(closes[index]) is None:
                        continue
                    rows.append({
                        "date": item_date.isoformat(),
                        "open": quote.get("open", [None] * len(timestamps))[index] if index < len(quote.get("open", [])) else None,
                        "high": quote.get("high", [None] * len(timestamps))[index] if index < len(quote.get("high", [])) else None,
                        "low": quote.get("low", [None] * len(timestamps))[index] if index < len(quote.get("low", [])) else None,
                        "close": closes[index],
                    })
                events = result.get("events") or {}
                splits = []
                for item in (events.get("splits") or {}).values():
                    if isinstance(item, Mapping):
                        splits.append({
                            "date": datetime.fromtimestamp(float(item.get("date")), tz=timezone.utc).date().isoformat(),
                            "numerator": item.get("numerator"),
                            "denominator": item.get("denominator"),
                        })
                dividends = []
                for item in (events.get("dividends") or {}).values():
                    if isinstance(item, Mapping):
                        dividends.append({
                            "date": datetime.fromtimestamp(float(item.get("date")), tz=timezone.utc).date().isoformat(),
                            "amount": item.get("amount"),
                        })
                normalized = normalize_research_price(rows, splits=splits, dividends=dividends)
                if not normalized:
                    raise ValueError("empty normalized research series")
                return {
                    "symbol": _symbol(symbol),
                    "market": str(market).lower(),
                    "currency": "USD" if str(market).lower() in {"us", "usa", "usd"} else "TWD",
                    "rows": normalized,
                    "source": f"Yahoo Chart raw OHLC ({chart_symbol}) + research-price contract v1",
                    "corporateActionStatus": "PASS",
                    "attempts": attempt + 1,
                }
            except Exception as error:  # noqa: BLE001 - diagnostic boundary
                failures.append(f"{chart_symbol}:{type(error).__name__}")
                if attempt + 1 < max(1, attempts):
                    sleep_fn(min(2 ** attempt, 8))
    return {
        "symbol": _symbol(symbol),
        "market": str(market).lower(),
        "currency": "USD" if str(market).lower() in {"us", "usa", "usd"} else "TWD",
        "rows": [],
        "source": None,
        "corporateActionStatus": "UNAVAILABLE",
        "status": "UNAVAILABLE",
        "reason": "; ".join(failures) or "history unavailable",
    }


def fetch_finmind_research_series(
    symbol: str,
    *,
    token: str | None,
    start: date,
    end: date,
    http_get: Any = None,
    timeout: float = 20,
) -> dict[str, Any] | None:
    """Fetch Taiwan raw OHLC through the authenticated research source.

    ``None`` means the caller should use its secondary raw-chart provider;
    malformed or empty responses are explicit unavailable contracts.
    """
    if not token:
        return None
    getter = http_get or requests.get
    try:
        response = getter(
            "https://api.finmindtrade.com/api/v4/data",
            params={
                "dataset": "TaiwanStockPrice",
                "data_id": _symbol(symbol),
                "start_date": start.isoformat(),
                "end_date": end.isoformat(),
                "token": token,
            },
            timeout=timeout,
        )
        response.raise_for_status()
        records = response.json().get("data", [])
        rows = [
            {
                "date": item.get("date"),
                "open": item.get("open"),
                "high": item.get("max"),
                "low": item.get("min"),
                "close": item.get("close"),
            }
            for item in records
            if isinstance(item, Mapping)
        ]
        normalized = normalize_research_price(rows)
        return {
            "symbol": _symbol(symbol),
            "market": "tw",
            "currency": "TWD",
            "rows": normalized,
            "source": "FinMind TaiwanStockPrice raw OHLC + research-price contract v1",
            "corporateActionStatus": "PASS",
            "attempts": 1,
        }
    except Exception as error:  # noqa: BLE001 - source boundary
        return {
            "symbol": _symbol(symbol),
            "market": "tw",
            "currency": "TWD",
            "rows": [],
            "source": None,
            "corporateActionStatus": "UNAVAILABLE",
            "status": "UNAVAILABLE",
            "reason": type(error).__name__,
        }


def fetch_research_series(symbol: str, *, market: str, start: date, end: date, token: str | None = None, http_get: Any = None) -> dict[str, Any]:
    """Apply the primary Taiwan source and raw-chart fallback policy."""
    if str(market).lower() in {"tw", "taiwan", "twd"} and token:
        primary = fetch_finmind_research_series(symbol, token=token, start=start, end=end, http_get=http_get)
        if primary and primary.get("rows"):
            return primary
    return fetch_yahoo_research_series(symbol, market=market, start=start, end=end, http_get=http_get)


def _quarter_index(value: date) -> int:
    return value.year * 4 + (value.month - 1) // 3


def previous_quarter_cutoff(value: date | None = None) -> date:
    """Return the last calendar day of the quarter before ``value``."""
    current = value or date.today()
    quarter_start_month = ((current.month - 1) // 3) * 3 + 1
    quarter_start = date(current.year, quarter_start_month, 1)
    return quarter_start - timedelta(days=1)


def _event_rows(events: Any, *, value_keys: tuple[str, ...]) -> dict[date, float]:
    result: dict[date, float] = {}
    if isinstance(events, Mapping):
        iterable = events.values()
    elif isinstance(events, (list, tuple)):
        iterable = events
    else:
        iterable = []
    for item in iterable:
        if not isinstance(item, Mapping):
            continue
        event_date = _as_date(item.get("date") or item.get("exDate") or item.get("ex_date"))
        if event_date is None:
            raw_timestamp = item.get("timestamp")
            try:
                event_date = datetime.fromtimestamp(float(raw_timestamp), tz=timezone.utc).date()
            except (TypeError, ValueError, OverflowError, OSError):
                event_date = None
        if event_date is None:
            continue
        raw_value = next((item.get(key) for key in value_keys if item.get(key) is not None), None)
        number = _finite(raw_value)
        if number is not None:
            result[event_date] = number
    return result


def normalize_research_price(
    rows: list[Mapping[str, Any]] | tuple[Mapping[str, Any], ...],
    *,
    splits: Any = None,
    dividends: Any = None,
) -> list[dict[str, Any]]:
    """Create split-adjusted and point-in-time total-return prices.

    Input rows must contain a date and a raw executable ``close``.  Split
    factors are applied only to dates before the event; dividends are added on
    the event date when building the total-return index.  Conflicting dates or
    invalid prices are rejected instead of being silently overwritten.
    """
    split_events = _event_rows(splits, value_keys=("ratio", "factor", "splitRatio"))
    if isinstance(splits, Mapping):
        split_events = {}
        for item in splits.values():
            if not isinstance(item, Mapping):
                continue
            event_date = _as_date(item.get("date") or item.get("exDate"))
            numerator = _finite(item.get("numerator"))
            denominator = _finite(item.get("denominator"))
            if event_date is not None and numerator and denominator:
                split_events[event_date] = denominator / numerator
            elif event_date is not None:
                ratio = _finite(item.get("ratio") or item.get("factor") or item.get("splitRatio"))
                if ratio and ratio > 0:
                    split_events[event_date] = ratio
    dividend_events = _event_rows(dividends, value_keys=("amount", "dividend", "cashAmount", "value"))

    by_date: dict[date, tuple[float, Mapping[str, Any]]] = {}
    for row in rows or []:
        if not isinstance(row, Mapping):
            continue
        item_date = _as_date(row.get("date"))
        close = _finite(row.get("close"))
        if item_date is None or close is None or close <= 0:
            continue
        if item_date in by_date and abs(by_date[item_date][0] / close - 1) > 1e-9:
            raise ValueError(f"conflicting close for {item_date.isoformat()}")
        by_date[item_date] = (close, row)
    if not by_date:
        raise ValueError("research series has no valid raw closes")

    result: list[dict[str, Any]] = []
    total_return: float | None = None
    previous_adjusted: float | None = None
    for item_date in sorted(by_date):
        raw_close = by_date[item_date][0]
        split_factor = 1.0
        for event_date, factor in split_events.items():
            if item_date < event_date:
                split_factor *= factor
        adjusted_close = raw_close * split_factor
        if previous_adjusted is None:
            total_return = adjusted_close
        else:
            dividend = dividend_events.get(item_date, 0.0)
            total_return *= (adjusted_close + dividend) / previous_adjusted
        previous_adjusted = adjusted_close
        result.append({
            "date": item_date.isoformat(),
            "open": _finite(by_date[item_date][1].get("open")),
            "high": _finite(by_date[item_date][1].get("high")),
            "low": _finite(by_date[item_date][1].get("low")),
            "close": raw_close,
            "splitAdjustedClose": adjusted_close,
            "totalReturnIndex": total_return,
        })
    return result


def _weekly_rows(rows: list[Mapping[str, Any]], *, price_key: str, currency: str = "TWD", fx_rows: list[Mapping[str, Any]] | None = None, cutoff: date | None = None) -> dict[tuple[int, int], tuple[date, float]]:
    fx: dict[date, float] = {}
    for row in fx_rows or []:
        item_date = _as_date(row.get("date"))
        value = _finite(row.get("close", row.get("price")))
        if item_date is not None and value is not None and value > 0:
            fx[item_date] = value
    result: dict[tuple[int, int], tuple[date, float]] = {}
    for row in rows or []:
        item_date = _as_date(row.get("date"))
        value = _finite(row.get(price_key))
        if item_date is None or value is None or value <= 0 or (cutoff and item_date > cutoff):
            continue
        if currency.upper() != "TWD":
            candidates = [item for item in fx if item <= item_date]
            if not candidates:
                continue
            value *= fx[max(candidates)]
        key = item_date.isocalendar()[:2]
        previous = result.get(key)
        if previous is None or item_date > previous[0]:
            result[key] = (item_date, value)
    return result


def weekly_research_series(
    rows: list[Mapping[str, Any]],
    *,
    price_key: str = "splitAdjustedClose",
    currency: str = "TWD",
    fx_rows: list[Mapping[str, Any]] | None = None,
    cutoff: date | str | None = None,
) -> list[dict[str, Any]]:
    """Return one completed, point-in-time research price per ISO week.

    Beta and Kelly must not accidentally consume daily rows as if they were
    weekly observations.  Keeping this conversion in the research-price
    layer makes the sampling frequency explicit and re-usable by both
    candidate builders.
    """
    cutoff_date = _as_date(cutoff)
    weekly = _weekly_rows(
        rows or [],
        price_key=price_key,
        currency=currency,
        fx_rows=fx_rows,
        cutoff=cutoff_date,
    )
    return [
        {"date": item_date.isoformat(), "close": value}
        for item_date, value in sorted(weekly.values(), key=lambda item: item[0])
    ]


def estimate_beta_policy(
    histories: Mapping[str, Mapping[str, Any]],
    benchmark_rows: list[Mapping[str, Any]],
    *,
    fx_rows: list[Mapping[str, Any]] | None = None,
    cutoff: date | str | None = None,
    min_observations: int = MIN_WEEKLY_OBSERVATIONS,
) -> dict[str, Any]:
    """Build a review-only candidate policy from validated research series."""
    cutoff_date = _as_date(cutoff) or previous_quarter_cutoff()
    benchmark = _weekly_rows(benchmark_rows, price_key="splitAdjustedClose", cutoff=cutoff_date)
    assets: dict[str, Any] = {}
    for raw_symbol, record in (histories or {}).items():
        symbol = _symbol(raw_symbol)
        if not symbol or symbol in FIXED_BETAS:
            continue
        rows = record.get("rows") if isinstance(record, Mapping) else None
        currency = str(record.get("currency", "TWD")) if isinstance(record, Mapping) else "TWD"
        weekly = _weekly_rows(rows or [], price_key="splitAdjustedClose", currency=currency, fx_rows=fx_rows, cutoff=cutoff_date)
        common = sorted(set(benchmark).intersection(weekly))
        asset_prices = [weekly[key][1] for key in common]
        benchmark_prices = [benchmark[key][1] for key in common]
        asset_returns = [asset_prices[index] / asset_prices[index - 1] - 1 for index in range(1, len(asset_prices))]
        benchmark_returns = [benchmark_prices[index] / benchmark_prices[index - 1] - 1 for index in range(1, len(benchmark_prices))]
        estimate = estimate_beta_from_returns(asset_returns, benchmark_returns, min_observations=min_observations)
        corporate_status = str(record.get("corporateActionStatus", "UNAVAILABLE")) if isinstance(record, Mapping) else "UNAVAILABLE"
        source = str(record.get("source", "")) if isinstance(record, Mapping) else ""
        if estimate.get("status") != "READY" or corporate_status != "PASS" or not source:
            assets[symbol] = {
                "status": "INSUFFICIENT_EVIDENCE",
                "reason": estimate.get("reason") or "corporate action or source evidence unavailable",
                "observations": estimate.get("observations", len(asset_returns)),
                "corporateActionStatus": corporate_status,
                "source": source or None,
            }
            continue
        assets[symbol] = {
            "status": "CANDIDATE",
            "beta": round(float(estimate["beta"]), 8),
            "observations": int(estimate["observations"]),
            "method": "paired_weekly_split_adjusted_twd_returns",
            "corporateActionStatus": corporate_status,
            "source": source,
            "market": str(record.get("market", "other")).lower(),
        }
    serial = json.dumps(assets, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return {
        "schemaVersion": POLICY_SCHEMA_VERSION,
        "status": "CANDIDATE" if any(item.get("status") == "CANDIDATE" for item in assets.values()) else "INSUFFICIENT_EVIDENCE",
        "approvalStatus": "PENDING",
        "policyVersion": f"candidate-{cutoff_date.isoformat()}",
        "benchmark": "006208.TW/TWD",
        "dataCutoff": cutoff_date.isoformat(),
        "assets": assets,
        "contentHash": hashlib.sha256(serial.encode("utf-8")).hexdigest(),
    }


def validate_active_policy_document(payload: Mapping[str, Any], *, as_of: date | None = None, min_observations: int = MIN_WEEKLY_OBSERVATIONS) -> tuple[dict[str, float], dict[str, Any] | None, str | None]:
    """Validate an approved policy before it can feed the live calculator."""
    if not isinstance(payload, Mapping) or payload.get("schemaVersion") != POLICY_SCHEMA_VERSION:
        return {}, None, "policy schema version mismatch"
    if str(payload.get("status", "")).upper() != "ACTIVE" or str(payload.get("approvalStatus", "")).upper() != "APPROVED":
        return {}, None, "policy is not approved and active"
    cutoff = _as_date(payload.get("dataCutoff"))
    today = as_of or date.today()
    if cutoff is None or cutoff > previous_quarter_cutoff(today):
        return {}, None, "policy cutoff is not point-in-time"
    if _quarter_index(today) - _quarter_index(cutoff) > 1:
        return {}, None, "policy is stale"
    assets = payload.get("assets")
    if not isinstance(assets, Mapping):
        return {}, None, "policy assets missing"
    canonical_assets = json.dumps(assets, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    expected_hash = hashlib.sha256(canonical_assets.encode("utf-8")).hexdigest()
    supplied_hash = str(payload.get("contentHash") or "")
    if supplied_hash and supplied_hash != expected_hash:
        return {}, None, "policy content hash mismatch"
    betas: dict[str, float] = {}
    for raw_symbol, record in assets.items():
        symbol = _symbol(raw_symbol)
        if symbol in FIXED_BETAS:
            continue
        if not isinstance(record, Mapping):
            return {}, None, f"invalid policy record for {symbol}"
        beta = _finite(record.get("beta"))
        observations = record.get("observations")
        if beta is None or beta < 0 or not isinstance(observations, int) or observations < min_observations:
            return {}, None, f"invalid Beta evidence for {symbol}"
        if str(record.get("corporateActionStatus", "")).upper() != "PASS":
            return {}, None, f"corporate action not validated for {symbol}"
        if not str(record.get("source", "")).strip():
            return {}, None, f"source missing for {symbol}"
        betas[symbol] = beta
    metadata = {
        "policyVersion": str(payload.get("policyVersion") or ""),
        "dataCutoff": cutoff.isoformat(),
        "contentHash": str(payload.get("contentHash") or ""),
        "benchmark": str(payload.get("benchmark") or "006208.TW/TWD"),
    }
    return betas, metadata, None


def load_active_beta_policy(path: str | Path | None = None, *, as_of: date | None = None) -> dict[str, Any]:
    policy_path = Path(path or DEFAULT_ACTIVE_POLICY_PATH)
    try:
        payload = json.loads(policy_path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {"status": "UNAVAILABLE", "quality": "policy_missing", "reason": "active Beta policy unavailable", "betas": {}, "metadata": None}
    betas, metadata, error = validate_active_policy_document(payload, as_of=as_of)
    if error:
        return {"status": "UNAVAILABLE", "quality": "policy_invalid", "reason": error, "betas": {}, "metadata": None}
    return {"status": "READY", "quality": "policy_complete", "reason": None, "betas": {**FIXED_BETAS, **betas}, "metadata": metadata}


def validate_active_kelly_document(payload: Mapping[str, Any], *, as_of: date | None = None) -> tuple[dict[str, Any] | None, str | None]:
    """Validate a manually approved quarterly Kelly parameter document."""
    if not isinstance(payload, Mapping) or payload.get("schemaVersion") != POLICY_SCHEMA_VERSION:
        return None, "Kelly policy schema version mismatch"
    if str(payload.get("status", "")).upper() != "ACTIVE" or str(payload.get("approvalStatus", "")).upper() != "APPROVED":
        return None, "Kelly policy is not approved and active"
    cutoff = _as_date(payload.get("dataCutoff"))
    today = as_of or date.today()
    if cutoff is None or cutoff > previous_quarter_cutoff(today):
        return None, "Kelly policy cutoff is not point-in-time"
    if _quarter_index(today) - _quarter_index(cutoff) > 1:
        return None, "Kelly policy is stale"
    mu = _finite(payload.get("mu"))
    sigma = _finite(payload.get("sigma"))
    limit = _finite(payload.get("halfKellyLimit"))
    if mu is None or sigma is None or limit is None or mu <= 0 or sigma <= 0 or limit <= 0:
        return None, "Kelly policy parameters are invalid"
    expected = quarterly_half_kelly(mu, sigma)
    if expected.get("status") != "CANDIDATE" or abs(float(expected["halfKellyLimit"]) - limit) > 1e-8:
        return None, "Kelly policy formula mismatch"
    return {
        "activeVersion": str(payload.get("activeVersion") or payload.get("policyVersion") or ""),
        "mu": float(expected["mu"]),
        "sigma": float(expected["sigma"]),
        "halfKellyLimit": float(expected["halfKellyLimit"]),
        "dataCutoff": cutoff.isoformat(),
        "approvalStatus": "APPROVED",
        "freshness": "current",
        "source": str(payload.get("source") or ""),
        "contentHash": str(payload.get("contentHash") or ""),
    }, None


def load_active_kelly_policy(path: str | Path | None = None, *, as_of: date | None = None) -> dict[str, Any]:
    policy_path = Path(path or DEFAULT_ACTIVE_KELLY_PATH)
    try:
        payload = json.loads(policy_path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {"status": "UNAVAILABLE", "quality": "policy_missing", "reason": "active Kelly policy unavailable", "policy": None}
    policy, error = validate_active_kelly_document(payload, as_of=as_of)
    if error:
        return {"status": "UNAVAILABLE", "quality": "policy_invalid", "reason": error, "policy": None}
    return {"status": "READY", "quality": "policy_complete", "reason": None, "policy": policy}
